version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.29
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: mongo
            uri: mongodb+srv://write-user:writeUser123Retry@nodecourse-zfafv.mongodb.net/redditDays
            database: redditDays
            migrations: false